# Generated by Django 4.1 on 2024-10-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeTCG', '0003_alter_card_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expansion',
            field=models.CharField(default='sin expansion', max_length=30),
            preserve_default=False,
        ),
    ]
